### PR TITLE
Add a new <TEAM>_mom gauge with component and status labels

### PR DESCRIPTION
**Pull request by OddBloke**
In addition the existing <TEAM>_mom_* gauges, this adds a single
<TEAM>_mom gauge with labels that allow us to decompose by component and
label at the prometheus level.

### CODE REVIEW

**Comment by powersj** [comment]
I may need you to show me how to clean this up in grafana. My understanding is if we were to import a metric (e.g. needs-merge, needs sync, etc.) with multiple labels, then each metric would then have lines added for each label. In this case 3, one for each component.

Is there a way to then sum them all up?

**Comment by OddBloke** [comment]
`sum(foundations_mom) by (status)` gives you:

```
{status="local"} | 76
{status="repackaged"} | 11
{status="needs-merge"} | 138
{status="modified"} | 230
{status="needs-sync"} | 25
{status="unmodified"} | 787
{status="total"} | 1267
```

or `sum(foundations_mom{status="needs-merge"})` gives you:

```
{} | 138
```

That said, you may want to confirm that you actually want to be tracking anything outside of main; AIUI, the list of packages that the scripting uses lists all the packages that have ever been in main and owned by a team; it is not necessarily representative of the packages you should care about today.

(@vorlonofportland may be able to confirm/deny this.)

**Comment by vorlonofportland** [comment]
While the numbers looked high to me, I see that there are 2402 source packages in main as of artful.  It's not impossible that 1267 is a real number for foundations-owned packages in main.

But yes, we do not want to be including non-main packages in our count for these purposes.

**Comment by vorlonofportland** [comment]
Looking at the generated stats.txt for Foundations:
2017-07-21 07:21 main needs-merge=127 unmodified=432 needs-sync=17 modified=152 repackaged=9 total=785 local=48
2017-07-21 07:21 restricted needs-merge=0 unmodified=1 needs-sync=0 modified=0 repackaged=0 total=1 local=0

So yes, that's 786 packages that should be reported for Foundations in artful, rather than the 1267 currently reported.  MoM already exposes this by component in the stats, so the metric should just filter out universe.

(And I argue this should be a straight filtering out, not "report as separate metrics", because by definition packages in the package-team-mapping that are no longer in main are not actually the responsibility of the named team.)

**Comment by powersj** [comment]
Is the better approach to 1) removing universe at the metric generation state or 2) only report main and universe values at the Grafana stage?

With option 1 we make Grafana straight forward, and less computation required
With option 2 we keep all the data and allow for potentially overreporting

**Comment by OddBloke** [comment]
@powersj In 1a25fb0, I've updated the code to only report `main`, but have left `component` as a label in the metric so that if we decide to include more than one component later we won't have to change the metric labels.

**Pull request merged**
