### PR TITLE
Add in a metric for the size of the current daily cloud image.

### PR DESCRIPTION
**Pull request by murraybd**
IMAGE_FORMAT could become a list with multiple different image formats if we want.

### CODE REVIEW

**Comment by OddBloke** [comment]
@murraybd I wonder if this would be better off using InfluxDB? That would allow us to import all of the image size history, which would be nice.

(The impression I get is that we're also trying to migrate off of Prometheus, due to its poor performance when (ab)used the way we use it. Perhaps @powersj can speak to that?)

**Comment by powersj** [comment]
Agreed on not using Prometheus. Due to the poor performance, limitations on prior data, and no way to backup the data easily using Influx is the way forward.

**Comment by murraybd** [comment]
Okay, I've switched over to using InfluxDB and tested it locally using juju.

> select * from cloud_images_sizes where arch = 'amd64'
name: cloud_images_sizes
time                arch  format    release size      type
----                ----  ------    ------- ----      ----
1517953056583310415 amd64 disk1.img artful  319619072 daily
1517953056583310415 amd64 disk1.img bionic  313720832 daily
1517953056583310415 amd64 disk1.img trusty  262472192 daily
1517953056583310415 amd64 disk1.img xenial  289669120 daily

**Comment by OddBloke** [comment]
One nice thing that InfluxDB allows us to do is store data points at a particular time. So instead of storing the most recent image size every hour, we can determine the size of the most recent image and store that _at the time the image was published_. (The serial of the image is, I think, enough for this.)

In a part-finished local metric, I have the following code:

```py
def _get_datetime_for_serial(serial: str) -> datetime:
    return datetime.strptime(serial[:8], '%Y%m%d')
```
which is used like this:
```py
product_datetime = _get_datetime_for_serial(product_dict['version_name'])
```
You should then just be able to pass that as the 'time' attribute in the point dict, and I think the InfluxDB library DTRT.

**Comment by OddBloke** [comment]
https://github.com/canonical-server/metrics/blob/master/metrics/docker_hub_images.py#L42 is an already in-repo example of doing this.

**Comment by murraybd** [comment]
If the image is unchanged, e.g. the daily image is from 2018-02-04, won't the time field be the same until there is a new daily image? How will this end up being displayed in grafana?

**Comment by OddBloke** [comment]
Yep, that's exactly what will happen (and InfluxDB will only store one data point for any given time field, so we don't end up duplicating data).

https://cloud.kpi.canonical.com/dashboard/db/foundations-internal?panelId=14&fullscreen (sorry external people) is an example of how we do this for another metric; it uses `SELECT last("full_size") FROM "docker_hub_images" WHERE $timeFilter GROUP BY time($interval), "suite" fill(previous)`; the `last` and `fill(previous)` are the key parts which give us the same graph we would get from pushing a data point at every run.

**Comment by OddBloke** [comment]
(@powersj Incidentally, I don't know if this is something you might want to switch the ISO metrics to do.)

**Comment by murraybd** [comment]
Neat, so I've switched the time field per your suggestion. So we now have the following:

> select * from cloud_images_sizes where arch = 'amd64'
name: cloud_images_sizes
time                arch  format    release size      type
----                ----  ------    ------- ----      ----
1516924800000000000 amd64 disk1.img artful  319619072 daily
1517443200000000000 amd64 disk1.img trusty  262472192 daily
1517788800000000000 amd64 disk1.img bionic  313720832 daily
1517788800000000000 amd64 disk1.img xenial  289669120 daily

**Pull request merged**
